### PR TITLE
Transaction: send gitcoins to MisterDA

### PR DESCRIPTION
**Pull request by TheLortex**
Hi, I am human because I don't know the result of `0x8DF930AAA + 0xEFE999E0A`, hence validating this transaction.

### CODE REVIEW

**Comment by maiste** [comment]
Sorry, you can't merge it, @MisterDA didn't prove is existence.

**Review by maiste — CHANGES_REQUESTED** [review]
Sorry, you can't merge it, @MisterDA didn't prove is existence.

**Comment by MisterDA** [comment]
I think, therefore I am.
Is this a sufficient proof of my existence?
Note that in my mind I'm the only one existing and the reality I experience might just be the product of a demon standing on my shoulder. I have to convince myself that you exist, too.

**Comment by maiste** [comment]
As explain in the protocol, a proof of existence by opening an issue is required:
> Each Github user starts with 10 Gitcoins, and can ask for them by opening an issue containing a proof of existence. 

My existence is proven by #4 and @TheLortex existence is in verification stage in #11.

**Review by maiste — APPROVED** [review]

**Pull request merged**
